audio_dir: "audio"
pull_timeout: "PT10S"
message_limit: 10
motion_resume_delay: "2m"
presence_clear_delay: "4m"
use_ws_security: false
presence_targets:
  - "V2061"
camera:
  ip: "10.0.0.12"
  username: "admin"
  password: "password"
router:
  base_url: "http://10.0.0.1"
  username: "telecomadmin"
  password: "password"
  lang: "english"
telegram:
  token: "BOT_TOKEN"
  chat_id: 123456789
